name: CLI compatibility

on:
  pull_request:

permissions:
  contents: read

jobs:
  clisemver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - uses: Duylamneuuu/clisemver@main
        with:
          command: '["node","./dist/cli.js"]'
          snapshot: .clisemver/snapshot.json
          fail-on: major
